### ISSUE TITLE
Short values related to IPTC cannot be written

### ISSUE THREAD

**Issue by hiranoqueworks** [kolesa-team/goexiv#2]
Short values related to IPTC cannot be written
Iptc.Application2.RecordVersion
Iptc.Envelope.ModelVersion
etc

// Does not result in an error
        err :=rimg.SetIptcString(v.Key, v.Value)
        if err != nil {
            dlog.Println(err.Error())
            return
        }

I was able to write a character string

**Comment by antonsergeyev** [comment]
Indeed there's no type checking or validation of the keys in this library.
It is possible to explicitly check the datatypes according to this list https://www.exiv2.org/iptc.html but we don't plan to implement this right now

**Comment by hiranoqueworks** [comment]
> Indeed there's no type checking or validation of the keys in this library.
> It is possible to explicitly check the datatypes according to this list https://www.exiv2.org/iptc.html but we don't plan to implement this right now

Confirmed.
Thank you for your reply.

**Comment by hiranoqueworks** [comment]
> Indeed there's no type checking or validation of the keys in this library.
> It is possible to explicitly check the datatypes according to this list https://www.exiv2.org/iptc.html but we don't plan to implement this right now

This code did the job, but
How is it?

helper.cpp
exiv2_image_set_iptc_string Method
		std::string skey = key;
		if (skey.compare(std::string("Iptc.Application2.RecordVersion")) == 0) {
		    Exiv2::Iptcdatum& tag = iptcData[key];
			Exiv2::Value::AutoPtr valueObject = Exiv2::Value::create(Exiv2::unsignedShort);
			valueObject->read(value);
			tag.setValue(valueObject.get());
		}

**Comment by antonsergeyev** [comment]
I'd rather just create an `exiv2_image_set_iptc_short` method that accepts short int instead of a string.
This way additional type conversion will be avoided, and `exiv2_image_set_iptc_string` stays cleaner.

You're welcome to submit a PR

**Comment by hiranoqueworks** [comment]
> I'd rather just create an `exiv2_image_set_iptc_short` method that accepts short int instead of a string.
> This way additional type conversion will be avoided, and `exiv2_image_set_iptc_string` stays cleaner.
> 
> You're welcome to submit a PR

How about this code?
Should I make a pull request with git?

void
exiv2_image_set_iptc_short(Exiv2Image *img, char *key, char *value, Exiv2Error **error)
{
	Exiv2::IptcData iptcData = img->image->iptcData();

	try {
		Exiv2::Iptcdatum& tag = iptcData[key];
		Exiv2::Value::AutoPtr valueObject = Exiv2::Value::create(Exiv2::unsignedShort);
		valueObject->read(value);
		tag.setValue(valueObject.get());

		img->image->setIptcData(iptcData);
		img->image->writeMetadata();
	} catch (Exiv2::Error &e) {
		if (error) {
			*error = new Exiv2Error(e);
		}
	}
}

**Comment by antonsergeyev** [comment]
yes, looks good to me

**Comment by hiranoqueworks** [comment]
> yes, looks good to me

**Comment by hiranoqueworks** [comment]
> > yes, looks good to me
I will send you all the necessary sources.

[short.zip](https://github.com/kolesa-team/goexiv/files/6340617/short.zip)

**Comment by antonsergeyev** [comment]
@hiranoqueworks just merged this to master branch
